### ISSUE TITLE
java.lang.IncompatibleClassChangeError 

### ISSUE THREAD

**Issue by ravi-coursera** [NaikSoftware/StompProtocolAndroid#10]
I am getting the following runtime error when connecting to server.
`mStompClient = Stomp.over(WebSocket.class, "ws://192.168.1.19:8080/app/hello");
 mStompClient.connect();` --> error is thrown at this line
"**java.lang.IncompatibleClassChangeError: The method 'void ua.naiksoftware.stomp.WebSocketsConnectionProvider.ua_naiksoftware_stomp_WebSocketsConnectionProvider_lambda$getLifecycleReceiver$3(rx.Subscriber)' was expected to be of type direct but instead was found to be of type virtual (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar**)" 

Gradle settings:
`
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

```
defaultConfig {
    applicationId "in.liberin.beacon"
    minSdkVersion 18
    targetSdkVersion 24
    versionCode 1
    versionName "1.0"
    jackOptions {
        enabled true
    }
}

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

}
`

Android Studio 2.1.1

**Comment by NaikSoftware** [comment]
What WebSocket library you use? (version)

**Comment by ravi-coursera** [comment]
These are the dependencies in the app gradle
`   compile 'com.android.support:support-v4:24.2.0'
    compile 'com.github.NaikSoftware:StompProtocolAndroid:1.0.11'
    compile 'org.java-websocket:java-websocket:1.3.1'`

**Comment by NaikSoftware** [comment]
Hm, try version 1.3.0

**Comment by ravi-coursera** [comment]
Still the same..
I am running it on Yu Yureka AO5510 handset.

**Comment by NaikSoftware** [comment]
Can not reproduce.
