### ISSUE TITLE
User name [null] or password is invalid.

### ISSUE THREAD

**Issue by zr940326** [NaikSoftware/StompProtocolAndroid#107]
Hello, I want to ask, where is the username and password, ActiveMQ opens the password access, I always the password and the user can not be empty.
![image](https://user-images.githubusercontent.com/17058316/43035564-a044890a-8d24-11e8-9dc8-0b186547d83b.png)

**Comment by zr940326** [comment]
**I try to use the following method, but still won't do.**


List<StompHeader> headerList = new ArrayList<>();
StompHeader loginHeader = new StompHeader("login", "user");
StompHeader passHeader = new StompHeader("passcode", "password");
headerList.add(loginHeader);
headerList.add(passHeader);

StompClient client = Stomp.over(...);
client.connect(headerList);

![image](https://user-images.githubusercontent.com/17058316/43035651-584e9490-8d26-11e8-8af9-98d3e12fa7b2.png)

**Comment by zr940326** [comment]
**I did try, still can't solve**

![image](https://user-images.githubusercontent.com/17058316/43035683-ea431e84-8d26-11e8-95cc-2370285f4f7c.png)
![image](https://user-images.githubusercontent.com/17058316/43035699-0d98f430-8d27-11e8-86f1-f8831bd9266a.png)

**Comment by forresthopkinsa** [comment]
For one thing, the code you've provided uses "passcode", whereas your log has the header "password". So this isn't the code running.

For another thing, it really quite looks like the server you're talking to is really just refusing your credentials. Is it possible that the user/pass are wrong?

Much more likely, it's expecting the credentials to be hashed or tokenized or something. You don't normally see protocols that ask for plaintext authentication.

**Comment by zr940326** [comment]
**Thank you very much, the problem has been solved, through consultation, I found that the key was wrong**
StompHeader loginHeader = new StompHeader("login", "value");
StompHeader passHeader = new StompHeader("passcode", "value");

**The key, must be the login and passcode, I will change it to the following, so always said my user name and password cannot be empty.**

![image](https://user-images.githubusercontent.com/17058316/43046635-5eea077a-8dfe-11e8-92f9-245e4967cfa4.png)
![image](https://user-images.githubusercontent.com/17058316/43046645-8530aefc-8dfe-11e8-87cc-edaab869b60f.png)
