### ISSUE TITLE
Store every subscriptions made by user then unsubscribe later

### ISSUE THREAD

**Issue by axellageraldinc** [NaikSoftware/StompProtocolAndroid#112]
Suppose I want to make a group chat app. Here's the flow :

1. User A enter group chat name (the group chat name will be used by other user to join [in other words, to subscribe]) --> Let's say the group chat name is `LJ`
2. Subscribe user A to `/topic/LJ`
3. User B join group chat `LJ`. Then subscribe user B to `/topic/LJ`.
4. User A creates other group chat called `TIF`. Then subscribe user A to `/topic/TIF`.
5. User A decides to leave group chat `TIF`.

I know that to unsubscribe client to a topic, store the `mStompClient.topic(....)` to `Disposable` object. But In my scenario, how to differentiate one `Disposable` with another? Considering they are in the same `activity`. Do I store the `Disposable` in local database? Or else?

Any suggestions will be really appreciated!

**Comment by axellageraldinc** [comment]
Here, suppose I have 2 activities named CreateChatRoomActivity.java and ChatRoomActivity.java.

CreateChatRoomActivity is used for entering chat room’s name (or in other words, creating a topic and subscribe the user to it).

ChatRoomActivity is used for chatting, chat bubble and stuff here.

We know that there’s only 1 activity that create and subscribing the user to a topic, that is CreateChatRoomActivity. The first time user visit CreateChatRoomActivity and create a chat room named A, save it to a Disposable (like you said). Than the second time user visit CreateChatRoomActivity and create another chat room named B, save it to a Disposable (like you said).

My confusion is how you can differentiate those two Disposables because they just live inside the activity at that moment. Once the activity is destroyed (because the user can close the app and do other things), no way to access Disposable topic A or Disposable topic B.

Are we on the same page?

**Comment by forresthopkinsa** [comment]
It sounds like your problem is with persisting objects past the Android activity lifecycle. You need to look into different places to store and pass around your objects. Your concern isn't with this library.

**Comment by axellageraldinc** [comment]
@forresthopkinsa alright then.. How about you? Do you have any suggestions about my problem? Because it will be easier if you have it and share instead me searching for how to store a `Disposable` object in my android

**Comment by forresthopkinsa** [comment]
It doesn't have to do with disposables at all, it has to do with application state management.

Seriously, just google something like "pass data between android activities" or, alternatively, "android single source of truth".

This is fundamental Android app design. If you want help with that, you need to be asking somewhere besides here. This is not the place for it.

Unless you're going to bring this conversation back on topic, I'm pinging @NaikSoftware to close this.

**Comment by axellageraldinc** [comment]
Ok thanks for the help :) @forresthopkinsa

**Comment by forresthopkinsa** [comment]
No problem; sorry I have to keep issues here on-topic. Good luck!
