### ISSUE TITLE
How to connect websocket when the server is https?

### ISSUE THREAD

**Issue by Le0nHsu** [NaikSoftware/StompProtocolAndroid#113]
The same server uri ，if it is http, i could connect to the websocket, but if it is https, the webscoket is closed,not opened. What should I do?

**Comment by Anotherdgf** [comment]
I tried,but this lib seems not to support ssl,you may need to do it yourself.

**Comment by NaikSoftware** [comment]
You must use wss:// protocol

**Comment by abhishektiwari-obsidiam** [comment]
And how exactly i can pass my okhttp client ? any example please.
I'm not able to connect with https url, it says OPENED,CONNECT and instantly CLOSED.
Connect
Emit lifecycle event: OPENED
Send STOMP message: CONNECT
    accept-version:1.1,1.2
    heart-beat:0,0
   
Publish open
Emit lifecycle event: CLOSED
Help me out.
