### ISSUE TITLE
Library ok but doesn't work with RabbitMQ broker

### ISSUE THREAD

**Issue by fuatse** [NaikSoftware/StompProtocolAndroid#12]
Hello, 

I tried with RabbitMQ as broker but it doesn't work. It only works when I use the simple broker and without the method SockJS().

Any help on that?

**Comment by NaikSoftware** [comment]
I not tested with RabbitMQ, but it in my plans..

**Comment by NaikSoftware** [comment]
I tried also RabbitMQ, and all works
