### ISSUE TITLE
NoSuchElementException in StompMessage.from

### ISSUE THREAD

**Issue by kevindesai777** [NaikSoftware/StompProtocolAndroid#135]
I am getting a NoSuchElementException in the `reader.skip("\\s")` line, My input data is 'o' when a new web socket connection is opened. 

```
public static StompMessage from(@Nullable String data) {
        if (data == null || data.trim().isEmpty()) {
            return new StompMessage(StompCommand.UNKNOWN, null, data);
        }
        Scanner reader = new Scanner(new StringReader(data));
        reader.useDelimiter("\\n");
        String command = reader.next();
        List<StompHeader> headers = new ArrayList<>();

        while (reader.hasNext(PATTERN_HEADER)) {
            Matcher matcher = PATTERN_HEADER.matcher(reader.next());
            matcher.find();
            headers.add(new StompHeader(matcher.group(1), matcher.group(2)));
        }

        reader.skip("\\s");

        reader.useDelimiter(TERMINATE_MESSAGE_SYMBOL);
        String payload = reader.hasNext() ? reader.next() : null;

        return new StompMessage(command, headers, payload);
    }
```

**Comment by NaikSoftware** [comment]
See this https://stomp.github.io/stomp-specification-1.2.html#STOMP_Frames

After headers must be \n
`frame               = command EOL
                      *( header EOL )
                      EOL
                      *OCTET
                      NULL
                      *( EOL )`

**Comment by epolar** [comment]
I am getting same exception, and my input data is :
> ERROR
message:Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is error="unauthorized_user", error_description="status 401 reading AuthClient#getAuthentication(String); content\c\n{"error"\c"invalid_token","error_description"\c"Access token expired\c eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTMxMzcyNzIsInVzZXJfbmFtZSI6IjczMDEyNzU2NDgiLCJhdXRob3JpdGllcyI6WyJJU19NRVJDSEFOVCJdLCJqdGkiOiI2ZTcxNTExMC0zMTRiLTQ0NTAtYjMxYy0yZTZhNjZlMGFkMTIiLCJjbGllbnRfaWQiOiJtb3JlY29pbiIsInNjb3BlIjpbInVzZXIiXX0.JtV80FXi9z0UPaiFzBCNfXxwQSeHhQtTCQ1IUEjKiCo"}"
content-length:0
>
> ��

```java
public static StompMessage from(@Nullable String data) {
        if (data == null || data.trim().isEmpty()) {
            return new StompMessage(StompCommand.UNKNOWN, null, data);
        }
        Scanner reader = new Scanner(new StringReader(data));
        reader.useDelimiter("\\n");
        String command = reader.next();
        List<StompHeader> headers = new ArrayList<>();

        while (reader.hasNext(PATTERN_HEADER)) {
            Matcher matcher = PATTERN_HEADER.matcher(reader.next());
            matcher.find();
            headers.add(new StompHeader(matcher.group(1), matcher.group(2)));
        }

        reader.skip("\n\n");

        reader.useDelimiter(TERMINATE_MESSAGE_SYMBOL);
        String payload = reader.hasNext() ? reader.next() : null;

        return new StompMessage(command, headers, payload);
    }
```

**Comment by zcl947694252** [comment]
我用Android客户端收到信息的时候就会报这个错 你们有解决吗

**Comment by saqibusmangithub** [comment]
Hello, I am also getting this exception **java.util.NoSuchElementException: java.util.NoSuchElementException** on line **reader.skip("\n\n");** , how can i resolve it ?  I am using 1.6.4 version of lib

` public static StompMessage from(@Nullable String data) {
        if (data == null || data.trim().isEmpty()) {
            return new StompMessage(StompCommand.UNKNOWN, null, data);
        }
        Scanner reader = new Scanner(new StringReader(data));
        reader.useDelimiter("\\n");
        String command = reader.next();
        List<StompHeader> headers = new ArrayList<>();

        while (reader.hasNext(PATTERN_HEADER)) {
            Matcher matcher = PATTERN_HEADER.matcher(reader.next());
            matcher.find();
            headers.add(new StompHeader(matcher.group(1), matcher.group(2)));
        }

        reader.skip("\n\n");

        reader.useDelimiter(TERMINATE_MESSAGE_SYMBOL);
        String payload = reader.hasNext() ? reader.next() : null;

        return new StompMessage(command, headers, payload);
    }`
