### ISSUE TITLE
Does is support wss?

### ISSUE THREAD

**Issue by helara** [NaikSoftware/StompProtocolAndroid#15]
I'm unable to connect using wss... does the library supports it?

**Comment by NaikSoftware** [comment]
Not tested with ssl

**Comment by erobic** [comment]
I attempted to connected using wss, but the connection got CLOSED immediately.

For us, the following changes solved it:
https://github.com/NaikSoftware/StompProtocolAndroid/pull/22

It is working for us, but I haven't tested it exhaustively!

**Comment by NaikSoftware** [comment]
Resolved in #22

**Comment by sandeepmanegs** [comment]
@erobic How to use Webconnectionprovider with StompClient? Can you please give me some hint?

**Comment by erobic** [comment]
@sandeepmanegs Sorry, but I don't think I understand the question fully. StompClient uses WebSocketsConnectionProvider internally. 

Do you want to use ConnectionProvider separately? That would not be necessary as Stomp already provides the functionalities we need. May be it is better to ask your specific question on stackoverflow!
