### ISSUE TITLE
JSOn-RPC Support Suspended From June2020

### ISSUE THREAD

**Issue by subbu-mobi** [NaikSoftware/StompProtocolAndroid#161]
Dear Team , 
We are writing to let you know that one or more of your Google Cloud projects are currently using either the JSON-RPC or Global HTTP Batch serving endpoint; both of which are scheduled to be shut down on August 12, 2020.

 I see that StompClient uses Json-RPC . How are you planning to support android.

**Comment by forresthopkinsa** [comment]
This library doesn't use _any_ GCP APIs. What are you talking about?

**Comment by subbu-mobi** [comment]
Sorry Team , 
i mistook it with another library

**Comment by forresthopkinsa** [comment]
Feel free to close this issue.

**Comment by subbu-mobi** [comment]
Mistook with another library , sorry for the incovenience

**Comment by forresthopkinsa** [comment]
No worries
