### ISSUE TITLE
How to add Lambda support?

### ISSUE THREAD

**Issue by dimonik** [NaikSoftware/StompProtocolAndroid#17]
Hi!

You are using lambdas extensively inside library,
what is your setup to enable them in AndroidStudio?

**Comment by NaikSoftware** [comment]
See Retrolambda library

31 окт. 2016 г. 11:38 ПП пользователь "dimonik" <notifications@github.com>
написал:

**Comment by dimonik** [comment]
Please, add this info to README.

I wasted couple hours trying to run this with Jack compiler...

**Comment by NaikSoftware** [comment]
Ok, but retrolambda declared as dependency in build.gradle

1 нояб. 2016 г. 10:45 ДП пользователь "dimonik" <notifications@github.com>
написал:
