### ISSUE TITLE
Topic subscription after server connect doesn't work

### ISSUE THREAD

**Issue by amit-vohra** [NaikSoftware/StompProtocolAndroid#19]
Subscribe to new topic doesn't work if connection is already made to server. I have subscribed to 3 topics, two of them were subscribed just after connect() call and I am able to get messages on these subscription. One of them subscribed after 5 sec of execution for which I am not able to get messages. Here are some client logs

11-07 19:04:29.799 23457-23577/********** D/StompClient: Subscribe path: /topic/**soc_man_1** id: 857c081e-7951-4a6e-905a-66b110586f5e
11-07 19:04:29.800 23457-23577/********** D/StompClient: Subscribe path: /topic/**soc_1** id: 90df4b01-c49e-4e7f-9349-93bae1c92800
11-07 19:04:29.822 23457-23612/********** D/WebSocketsConnectionProvider: Emit lifecycle event: OPENED
11-07 19:04:29.827 23457-23612/********** D/WebSocketsConnectionProvider: Emit STOMP message: CONNECTED
11-07 19:04:34.094 23457-23457/********** D/StompClient: Subscribe path: /topic/**topic_1** id: 689453df-aabe-448f-be2a-b98bb50bdf32

Client is able to get messages from **soc_man_1** and **soc_1** topics but not from **topic_1**.

**Comment by amit-vohra** [comment]
I think this issue is because of missing .subscribe() call against send() api in StompClient::subscribePath(). Due to this actual send() on WebSocketClient is not getting called.

**Comment by amit-vohra** [comment]
I have made the changes locally and verified the fix. It works after adding .subscribe() in StompClient::subscribePath().

**Comment by amit-vohra** [comment]
I think StompClient::unsubscribePath() is also broken.

**Comment by 9to9** [comment]
i can confirm this is work, if we add subcribe() after subscribePath()

**Comment by SarojMaharjan** [comment]
Is this issue still unsolved? I require to subscribe after I receive response from the server but the after subscribing I can't receive the response from server.
