### ISSUE TITLE
Unrecognized token 'CONNECT'

### ISSUE THREAD

**Issue by Ivajkee** [NaikSoftware/StompProtocolAndroid#193]
When connecting, spring boot(2.3.4) displays an error Unrecognized token 'CONNECT': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false'), why? thx

**Comment by satyamk-android** [comment]
How it is fixed as I'm still facing it while connecting?

**Comment by forresthopkinsa** [comment]
You're connecting to the wrong endpoint
