### ISSUE TITLE
i user your lib，but always closed，can you help me

### ISSUE THREAD

**Issue by oemers** [NaikSoftware/StompProtocolAndroid#2]
here is the log：
![qq 20160520151815](https://cloud.githubusercontent.com/assets/5078768/15420258/1faa6c0c-1e9e-11e6-80b7-d10bc8dd50d0.png)

**Comment by NaikSoftware** [comment]
@oemers , after some time (1 minute for example) or at once?

**Comment by oemers** [comment]
closed at once。here is my code：
mStompClient = Stomp.over(org.java_websocket.WebSocket.class, wsuri);
				mStompClient.connect();
				/*mStompClient.topic("/topic/course_1").subscribe(new Action1<StompMessage>() {

					@Override
					public void call(StompMessage topicMessage) {
						System.out.println("这里是干什么的");
						Log.d(TAG, topicMessage.getPayload());
					}
				});
				mStompClient.send("/app/hello", "My first STOMP message!").subscribe();*/
				mStompClient.lifecycle().subscribe(new Action1<LifecycleEvent>() {

					@Override
					public void call(LifecycleEvent lifecycleEvent) {
						switch (lifecycleEvent.getType()) {

				        case OPENED:
				            Log.d(TAG, "Stomp connection opened");
				            mStompClient.topic("/topic/course_1").subscribe(new Action1<StompMessage>() {

								@Override
								public void call(StompMessage topicMessage) {
									System.out.println("这里是干什么的");
									Log.d(TAG, topicMessage.getPayload());
								}
							});
				            break;

				        case ERROR:
				            Log.e(TAG, "Error", lifecycleEvent.getException());
				            break;

				        case CLOSED:
				             Log.d(TAG, "Stomp connection closed");
				             break;
				    }
					}
				});

**Comment by NaikSoftware** [comment]
@oemers, library not tested with ActiveMQ backend. Try pass session id as stomp header with your messages. Also you can set breakpoint in WebSocket library (method onClose) and view close reason if server provided and websocket error code

**Comment by oemers** [comment]
onClose｛code=1000，reason=“”｝     and then can you tell me how "Try pass session id as stomp header with your messages"        like this?

Map<String, String> map = new HashMap<String, String>();
map.put("??", "???");
mStompClient = Stomp.over(org.java_websocket.WebSocket.class, wsuri,map );

**Comment by NaikSoftware** [comment]
@oemers , no, 
```java
StompMessage msg = new StompMessage(StompCommand.SEND, <headers here>, payload);
mStompClient.send(msg)
```

**Comment by NaikSoftware** [comment]
Or possibly server configured to close connection after N seconds. I fixed same problem on my Nginx proxy server. Nginx close connection after 1m by default..

**Comment by oemers** [comment]
can I add your Facebook to facilitate contact？  

 my:Oemers  Ren 
![qq 20160520170428](https://cloud.githubusercontent.com/assets/5078768/15422831/f6d8564a-1eac-11e6-97b8-d1a180faf19a.png)

**Comment by oemers** [comment]
haha，i get it success, because need this in the StompClient：
headers = new ArrayList<StompHeader>();
headers.add(new StompHeader(StompHeader.DESTINATION,"/topic/course_1"));
mConnectionProvider.send(new StompMessage(StompCommand.SUBSCRIBE,headers,null).compile())
                    		.subscribe();

but i have problem : how can i get the message in the Activity?

**Comment by NaikSoftware** [comment]
@oemers , hm, its already implemented, check the code [StompClient.java#L153](https://github.com/NaikSoftware/StompProtocolAndroid/blob/master/lib/src/main/java/ua/naiksoftware/stomp/client/StompClient.java#L153)
Its method called when you call `topic(...)` here [StompClient.java#L133](https://github.com/NaikSoftware/StompProtocolAndroid/blob/master/lib/src/main/java/ua/naiksoftware/stomp/client/StompClient.java#L133)

**Comment by oemers** [comment]
hha,yes,you are right!      so  how can i get the message in the Activity, when server give me a message?      i do not know how to register a listen to get new message!  can you give me some example code?

**Comment by NaikSoftware** [comment]
Yes,
```java
mStompClient.topic("/topic/course_1").subscribe(new Subscriber<StompMessage>() {
            @Override
            public void onCompleted() {
            }

            @Override
            public void onError(Throwable e) {
            }

            @Override
            public void onNext(StompMessage stompMessage) {
                String receivedMessage = stompMessage.getPayload();
                // receivedMessage contains content sended from server
            }
        });
```

**Comment by oemers** [comment]
yes，you are right！  but the onNext call twice always when new message come？ i do not know what happed

**Comment by oemers** [comment]
haha, i know what the problem ,because i 'subscribePath' twice ！ i  have 'subscribePath' in the StompClient ,  thank you very much, you solve my probleam perfect！memeda！

**Comment by baopengjian** [comment]
Can you show the whole code please？And what‘s the type of uri ? start with http or wss

**Comment by forresthopkinsa** [comment]
@baopengjian Please don't revive dead issues
