### ISSUE TITLE
Cant execute from UI thread

### ISSUE THREAD

**Issue by 9to9** [NaikSoftware/StompProtocolAndroid#20]
I tried to run stompclient.send(), inside button.onclicklistener but It doesnt execute, even when i try using asynctask or new thread inside button.onclicklistener.Any suggestion for this?

**Comment by NaikSoftware** [comment]
Without new thread working?

9 нояб. 2016 г. 1:33 ПП пользователь "9to9" <notifications@github.com>
написал:

**Comment by 9to9** [comment]
Not working even with or without thread, its never arrive at my server, but if i put it outside button.setOnClickListener, its working, and hit my server. Have some thing todo with UI thread that block it maybe?

**Comment by 9to9** [comment]
Aaah its working, i forgot, to add subcribe(), so it must be stomp.send().subcribe(). Sorry bro, thx for your response
