### ISSUE TITLE
Trim header 

### ISSUE THREAD

**Issue by EmmanuelVinas** [NaikSoftware/StompProtocolAndroid#23]
The pattern to parse header is not flexible. It does not allow spaces after or before ":"
Some backend libraries add a space after the ":" 
It may be possible to easily fix this by changing the pattern from 
"([^:\s]+):([^:\s]+)" to "([^:\s]+)([\s]*):([\s]*)([^:\s]+)"

And so.
"destination: /path" will work
"destination: /path" will work
"destination : /path" will work
"destination: " won't work

**Comment by NaikSoftware** [comment]
You pattern wrong.
Not working for `key:value`

**Comment by NaikSoftware** [comment]
Fixed in #7a49472c0d00efc715cd03f7c0e54944cab1b685

**Comment by EmmanuelVinas** [comment]
you are right, github was hidden the "*", bad copy/paste in the PR. Thanks
