### ISSUE TITLE
gridle issue

### ISSUE THREAD

**Issue by JihadIsmail** [NaikSoftware/StompProtocolAndroid#26]
Hello,
I can't resolve your library in android studio.
 Failed to resolve: com.github.NaikSoftware:StompProtocolAndroid:1.1.5

**Comment by NaikSoftware** [comment]
Add jitpack repo in project-level gradle
``` groovy
repositories { 
    jcenter()
    maven { url "https://jitpack.io" }
}
```

**Comment by JihadIsmail** [comment]
Ok, Thanks. I should put it at " all projects{}"
