### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by JihadIsmail** [NaikSoftware/StompProtocolAndroid#27]
Hello,
when I check "mWebSocket".isConnected(), I always get "false" !!
why the connection is never established?!

I try to stablish it over:
mStompClient = Stomp.over(WebSocket.class,"http:// server Ip address:port/notification-websocket");

also when I try:
mStompClient = Stomp.over(WebSocket.class,"ws:// server Ip address:port/notification-websocket");

and I am sure that the server is opened.

**Comment by NaikSoftware** [comment]
You should call mStompClient.connect();

**Comment by JihadIsmail** [comment]
Yea, I call it before "mWebSocket".isConnected()"!!

I also tried to subscribe on the topic before calling "mStompClient.connect();" and I sill got "False"!, I don't know why?
I follow your example as it is and test that my server is sending and receiving messages correctly.

**Comment by NaikSoftware** [comment]
@JihadIsmail, `connect` works asyncronously. StompClient goes to state `connected` after some time. You can subscribe to topics before connect., they are  will subscribed after connection established.
