### ISSUE TITLE
What is "topicMessage"? 

### ISSUE THREAD

**Issue by hoanghunguet** [NaikSoftware/StompProtocolAndroid#3]
May I ask you "What is "topicMessage"? " 
On below code:
mStompClient.topic("/topic/greetings").subscribe(topicMessage -> {
     Log.d(TAG, topicMessage.getPayload());
 });
Tks so much.

**Comment by oemers** [comment]
@hoanghunguet  like this:
`mStompClient.topic("/topic/greetings").subscribe(new Action1<StompMessage>() {
			@Override
			public void call(StompMessage topicMessage) {
				Log.d(TAG, topicMessage.getPayload());
			}
		});`

**Comment by oemers** [comment]
@hoanghunguet  like this:
`
mStompClient.topic("/topic/greetings").subscribe(new Action1<StompMessage>() {
			@Override
			public void call(StompMessage topicMessage) {
				Log.d(TAG, topicMessage.getPayload());
			}
		});
`

**Comment by hoanghunguet** [comment]
I don't build spring project and android project.You can help me send 2 project to email: hoanghung.chelseafc@gmail.com ?
Tks so much.
