### ISSUE TITLE
RabbitMQ stomp Draft17 refuses handshake

### ISSUE THREAD

**Issue by acsadam0404** [NaikSoftware/StompProtocolAndroid#30]
When connecting to a RabbitMQ stomp server (rabbit stomp plugin enabled) the library fails to connect. The close reason is: draft org.java_websocket.drafts.Draft_17@5f489ba refuses handshake

**Comment by NaikSoftware** [comment]
I tested on Spring STOMP over RabbitMQ transport and its worked for me..

**Comment by acsadam0404** [comment]
RabbitMQ has a plugin for stomp (https://www.rabbitmq.com/stomp.html). That is what's not working. Both web client and spring client (on desktop) works, but yours are the only real solution for android.

**Comment by NaikSoftware** [comment]
Ok, i will investigate this problem

**Comment by NaikSoftware** [comment]
You can try other Draft. In you own ConnectionProvider

**Comment by acsadam0404** [comment]
I tried all drafts and tried to create my own, but i didn't succeed. The problem is in Draft_10 acceptHandshakeAsClient. It's not matched because in

```
	if( !request.hasFieldValue( "Sec-WebSocket-Key" ) || !response.hasFieldValue( "Sec-WebSocket-Accept" ) )
			return HandshakeState.NOT_MATCHED;
```

response doesn't have "Sec-WebSocket-Accept". I tried without this check, but then I get bad rsv.

**Comment by acsadam0404** [comment]
Found the solution here: http://stackoverflow.com/questions/29217428/rabbitmq-web-stomp-without-sockjs . Overall: use the /stomp/websocket endpoint not the /stomp.
