### ISSUE TITLE
An stomp client connection issue in the Android 5.0

### ISSUE THREAD

**Issue by alysenko94** [NaikSoftware/StompProtocolAndroid#34]
Hi, @NaikSoftware.
I have an issue with a stomp client connection which it's reproduced only in the Android 5.0: when I call a method connect() of the StompClient class I don't have any lifecycle event as response.
There were events after call the method and all works fine in Android versions that lower than 5.0 and 5.1 or higher versions.
Have You faced with same issue? What did You do? :)
Hope to hear from You soon.

**Comment by NaikSoftware** [comment]
I am not faced with this issue.. Code not use any OS specific features..

**Comment by alysenko94** [comment]
Oh, okey :( I'm still searching what is the problem.
I compared logs of an app with Android 6.0.1 and 5.0.0 and found one difference. There were next entries for Android 6.0.1:
"D/WebSocketsConnectionProvider: onWebsocketHandshakeReceivedAsClient with response: 101 
D/WebSocketsConnectionProvider: onOpen with handshakeData: 101".
And there weren't any entries about ws connection in the Android 5.0.0.

**Comment by alysenko94** [comment]
I tried to connect to local ws server and got success.
And when I tried to connect to remote ws server I was waiting for initiating of the connection.
So it hardly is the problem of the library)
