### ISSUE TITLE
Stomp connection closed before opening

### ISSUE THREAD

**Issue by rajashripawar11** [NaikSoftware/StompProtocolAndroid#36]
I am getting below error,

onClose: code=-1 reason=draft org.java_websocket.drafts.Draft_17@5ece006 refuses handshake remote=false

 Emit lifecycle event: CLOSED

Not able to open connection with server, used same code. Help me to sort the issue.

**Comment by NaikSoftware** [comment]
Check the client and server examples https://github.com/NaikSoftware/StompProtocolAndroid/tree/master/example-client

**Comment by rajashripawar11** [comment]
Thanks for reply. I have used already used above link to implement.
Below is my code,

       mStompClient = Stomp.over(WebSocket.class, strUri);
        mStompClient.lifecycle()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(lifecycleEvent -> {
                    switch (lifecycleEvent.getType()) {
                        case OPENED:
                            toast("Stomp connection opened");
                            break;
                        case ERROR:
                            Log.e(TAG, "Stomp connection error", lifecycleEvent.getException());
                            toast("Stomp connection error");
                            break;
                        case CLOSED:
                            toast("Stomp connection closed");
                            break;
                    }
                });

        mStompClient.topic("/feed/getFeed")
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(topicMessage -> {
                    Log.d(TAG, "Received " + topicMessage.getPayload());
                });

        mStompClient.connect();

Below is error,

ua.naiksoftware.stompclientexample D/WebSocketsConnectionProvider: onClose: code=-1 reason=draft org.java_websocket.drafts.Draft_17@605966 refuses handshake remote=false
02-28 11:39:56.183 6787-6861/ua.naiksoftware.stompclientexample D/WebSocketsConnectionProvider: Emit lifecycle event: CLOSED
02-28 11:39:56.193 6787-6787/ua.naiksoftware.stompclientexample I/MainActivity: Stomp connection closed

**Comment by rajashripawar11** [comment]
It is working with test Url : ws://echo.websocket.org but does not work with my server url.

**Comment by ofirmiron** [comment]
I had the same problem. In the Android app, use the URL: **ws:**//YOUR_IP:PORT/ENDPOINT/**websocket**

The ENDPOINT is the one you specify in the WebSocketConfig : registerStompEndpoints

In my example, it is ws://192.168.29.166:8080/app/websocket

Hope this helps.

**Comment by hant35** [comment]
I had the same problem. Can not connect and send message.

**Comment by forresthopkinsa** [comment]
@hant35 Read through #49 and let me know if it applies to your issue.

**Comment by DenisBarnutiu** [comment]
did someone find a fix ?

**Comment by OmarAlgo** [comment]
@rajashripawar11 i am also stuck in this same issue. Did you find any solution regarding this error?
