### ISSUE TITLE
Cannot Send or Subscribe from android client

### ISSUE THREAD

**Issue by gryphonest** [NaikSoftware/StompProtocolAndroid#38]
hi... this is my code from android application..
**Constans.java**
`public class Constants {
    public static final String BASEURL = "ws://satubangau.com:61614/stomp";
    public static final String OUT = "hello";
    public static final String IN = "hello";
}`

**StompActivity.java**
`public class StompActivity extends AppCompatActivity {
    private final String TAG = this.getClass().getSimpleName().toUpperCase();
    private StompClient mStompClient;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_stomp);
        MessageModel model = new MessageModel();
        model.setName("You know who");
        model.setContent("This is last message");
        model.setFrom("C");
        model.setSessiondId("23487239423947234987239");
        Gson gson = new Gson();
        String messageJson = gson.toJson(model);
        mStompClient = Stomp.over(WebSocket.class, Constants.BASEURL);
        mStompClient.connect();
        if (mStompClient.isConnected()){
            Log.d("aaaa : ","onCreate: connected");
        }
        mStompClient.topic("/topic/hello").subscribe(message -> {
            Log.d("dddd - ", "Received "+message.toString());
        });
        mStompClient.send("/app/hello", "asdfasdfasdfs ").subscribe();
        mStompClient.lifecycle().subscribe(lifecycleEvent -> {
            switch (lifecycleEvent.getType()) {
                case OPENED:
                    Log.d(TAG, "Stomp connection opened");
                    break;
                case ERROR:
                    Log.e(TAG, "Error", lifecycleEvent.getException());
                    break;
                case CLOSED:
                    Log.d(TAG, "Stomp connection closed");
                    break;
            }
        });
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mStompClient.disconnect();
    }
}`

this is my log after run the code.

`02-28 17:12:41.073 30511-31452/com.redcircleapps.websockettest D/WebSocketsConnectionProvider: Emit lifecycle event: OPENED
02-28 17:12:41.078 30511-31452/com.redcircleapps.websockettest D/STOMPACTIVITY: Stomp connection opened
02-28 17:12:41.373 30511-31452/com.redcircleapps.websockettest D/WebSocketsConnectionProvider: onMessage: CONNECTED
                                                                                               server:ActiveMQ/5.11.0
                                                                                               heart-beat:0,0
                                                                                               session:ID:li1447-147.members.linode.com-44125-1487917479342-2:103
                                                                                               version:1.0
                                                                                               
                                                                                               ��
02-28 17:12:41.373 30511-31452/com.redcircleapps.websockettest D/WebSocketsConnectionProvider: Emit STOMP message: CONNECTED
                                                                                               server:ActiveMQ/5.11.0
                                                                                               heart-beat:0,0
                                                                                               session:ID:li1447-147.members.linode.com-44125-1487917479342-2:103
                                                                                               version:1.0
                                                                                               
                                                                                               ��`

so the url is **domain:61614/stomp**
in your documentation, your url was **ws://localhost:8080/app/hello/websocket**

then what?

this is my spring websocket code configuration. iam using default configuration ...so still use **/stomp**
**ChatController.groovy**

`class ChatController {
    SimpMessagingTemplate brokerMessagingTemplate
    def corporateUserService
    def index={
    }
    @MessageMapping("/hello")
    @SendTo("/topic/hello")
    protected String hello(DestinationUser map) {
        println "map = "+map
        brokerMessagingTemplate.convertAndSend "/topic/hello", 'Nama : '+map.name+"<br>Content : "+map.content+"<br>Session Id : "+map.sessiondId+"<br>From : "+map.from
    }
}`

what must i do?

**Comment by NaikSoftware** [comment]
If you use spring with stomp over ActiveMQ, you must connect to ws://<you spring application url and port>/<you spring stomp endpoint>/websocket

Suffix `/websocket` - is force use transport websocket for spring SockJS.

I using library now only with SpringBoot backend. Not tested with direct connect to AciveMQ stomp

**Comment by gryphonest** [comment]
so every i want to send message, the url like this? **ws://localhost:8080/stomp/websocket**

`    @MessageMapping("/hello")
    @SendTo("/topic/hello")`

and
**localhost:8080** is my application url
**/stomp** is my endpoint configuration `stompEndpointRegistry.addEndpoint("/stomp").withSockJS()`

**/websocket** what is this?

**Comment by gryphonest** [comment]
i cannot get any log when i try to connect with this url

1. **ws://localhost:8080/stomp/websocket**
2. **ws://localhost:8080/websocket**
3. **ws://localhost:8080/app/hello/websocket**

**Comment by NaikSoftware** [comment]
@gryphonest It is the right url ws://localhost:8080/stomp/websocket, but in android emulator you must use ip `10.0.2.2` instead `localhost`

**Comment by gryphonest** [comment]
oh, its working now..thank you
