### ISSUE TITLE
java.lang.IncompatibleClassChangeError: 

### ISSUE THREAD

**Issue by kalkrishnan** [NaikSoftware/StompProtocolAndroid#41]
I had been using this library to connect to my Stomp server successfully for a while. However recently I restarted my project and have been getting the below error, not sure why:

 java.lang.IncompatibleClassChangeError: The method 'void ua.naiksoftware.stomp.WebSocketsConnectionProvider.ua_naiksoftware_stomp_WebSocketsConnectionProvider_lambda$getLifecycleReceiver$3(rx.Subscriber)' was expected to be of type direct but instead was found to be of type virtual (declaration of 'ua.naiksoftware.stomp.WebSocketsConnectionProvider' appears in /data/app/com.gymtime.kalyank.gymtime-1/base.apk)
                      at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$lambda$3(WebSocketsConnectionProvider.java)
                      at ua.naiksoftware.stomp.WebSocketsConnectionProvider$$Lambda$6.call(Unknown)
                   
This is thrown during connect below:

   mStompClient = Stomp.over(WebSocket.class, "ws://10.0.2.2:8080/messages/websocket");
        mStompClient.connect();

Any help is appreciated.

**Comment by NaikSoftware** [comment]
If you are use latest version of lib (1.2.1+) you must use latest version of web socket lib (compile "org.java-websocket:java-websocket:1.3.2"), try update if have old version.

**Comment by kalkrishnan** [comment]
thanks! I also had to remove the following:

      jackOptions {
            enabled true
      }
