### ISSUE TITLE
StompClient timeout on connect()

### ISSUE THREAD

**Issue by steviemo** [NaikSoftware/StompProtocolAndroid#50]
Hey @NaikSoftware - if the websocket server isn't available at the point to attempting to connect() no lifecycle event is fired and the Rx thread hangs. I think this is a bug.

Would it be possible to pass a max timeout parameter on connect or this there workaround on Rx side of things where I could implement a timeout?

Thanks,
Stephen

**Comment by steviemo** [comment]
What do you guys think of this issue? Should I be handling this myself client side somehow instead?

**Comment by forresthopkinsa** [comment]
Are you using OkHttp or JWS?

**Comment by steviemo** [comment]
Hey - I'm using JWS:
compile 'org.java-websocket:Java-WebSocket:1.3.4'
compile 'com.github.NaikSoftware:StompProtocolAndroid:1.4.1'

**Comment by forresthopkinsa** [comment]
Try using OkHttp (it's a really simple switch) and see if anything changes.

**Comment by steviemo** [comment]
Yep OkHttp does the trick - it throws an error straight away. I was looking the JWS impl and this lib does pass connection timeout of 0 but it doesn't seem to take effect - takes about 60secs for the connection to time out.

**Comment by forresthopkinsa** [comment]
Really good to know. Thanks!
