### ISSUE TITLE
Gradle Build Fails

### ISSUE THREAD

**Issue by SheikhZayed** [NaikSoftware/StompProtocolAndroid#59]
Hello,for me the gradle build fails when i include this 
    compile 'com.github.NaikSoftware:StompProtocolAndroid:1.1.5'

**Comment by forresthopkinsa** [comment]
What errors does it throw? What environment are you running this in; what version of the Android plugin, what version of Java are you compiling with, are you using Retrolambda / Jack, etc

We need more details.

**Comment by SheikhZayed** [comment]
error : Failed to resolve: com.github.NaikSoftware:StompProtocolAndroid:1.1.5
Environment : developing an android stomp client for spring backend with JDK 1.8 and gradle 3-alpha9,
not using retrolambda/jack instead using native java8 support for in android studio 3.0

**Comment by NaikSoftware** [comment]
Do not use gradle plugin 3 alpha or beta. I have problems on all projecth with them

**Comment by SheikhZayed** [comment]
It Works! :+1:

**Comment by forresthopkinsa** [comment]
@SheikhZayed Let me know if you need to use Gradle Plugin v3+, there's a fork for that

**Comment by NaikSoftware** [comment]
I have tried to migrate project from retrolambda to android gradle plugin 3.0 beta2 and have strange errors - android studio can not recognize some attributes in layout xml :)

**Comment by SheikhZayed** [comment]
@forresthopkinsa yes i would like to use,could you please tell .
@NaikSoftware why are you still using retrolambda,when AS3.0 supports java8 out of the box

**Comment by NaikSoftware** [comment]
@SheikhZayed because Gradle plugin 3+ very unstable

**Comment by SheikhZayed** [comment]
cool,lets wait for a stable build soon :1st_place_medal:

**Comment by forresthopkinsa** [comment]
If you decide to use Native Java 8 support or the JACK toolchain, try using the fork:

`compile 'com.github.forresthopkinsa:StompProtocolAndroid:1.3.2-RC1'`

and **please** let me know your results.

**Comment by SheikhZayed** [comment]
@forresthopkinsa thanks for the tip,but it still fails

**Comment by forresthopkinsa** [comment]
@SheikhZayed Yeah but I need to know what you mean by that. What fails? What errors does it give? I can fix it if you give me some more info.

I've been using Native Java 8 with Gradle plugin 3+ for weeks with zero issues.

**Comment by SheikhZayed** [comment]
@forresthopkinsa will update you soon ..

**Comment by forresthopkinsa** [comment]
@SheikhZayed Any updates>

**Comment by forresthopkinsa** [comment]
@SheikhZayed Any updates?

**Comment by SheikhZayed** [comment]
@forresthopkinsa yes,that worked.i was bit occupied with other work.sorry for not updating you :)

**Comment by forresthopkinsa** [comment]
@SheikhZayed Awesome! Just so you know, it's been updated from `1.3.2-RC1` to `17.09.1` since I made that comment. Also, be sure to read the [changes](https://github.com/forresthopkinsa/StompProtocolAndroid#changes-in-this-fork) list, because that fork is not 100% compatible with code written for this upstream.
