### ISSUE TITLE
How to unsubscribe a topic when exit from a room?

### ISSUE THREAD

**Issue by deepahoy** [NaikSoftware/StompProtocolAndroid#60]
Actually the problem is, when i am subscribing a room and then exits from it remains subscribed . I want to unsubscribe it on exit. How should I do ??

**Comment by NaikSoftware** [comment]
Call unsubscribe in onDestroy or onStop of you Activity or Fragment

**Comment by deepahoy** [comment]
can you please post with syntax?? I have tried but not succeed.

**Comment by forresthopkinsa** [comment]
When initializing:

``` java
client = Stomp.over(...);
client.connect();
```

Now, in your onDestroy() or equivalent:

``` java
client.disconnect();
```

Can you elaborate on what you have tried and how it's not working?

**Comment by deepahoy** [comment]
I have subscribed to room by using this code : 

mStompClient.topic("/topic/room/" + roomId)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(topicMessage -> {
                    Log.d(TAG, "Received Room " + topicMessage.getPayload());
                    parseMessage(topicMessage.getPayload());
                });

but mStompClient.disconnect() is not unsubscribing this topic.

**Comment by forresthopkinsa** [comment]
Can you run an `.isConnected()` check? It's very likely that you're not completely disconnecting.

``` java
.subscribe(msg -> {
  Log.d(TAG, "Client is " + (mStompClient.isConnected() ? "connected" : "disconnected"))
});
```

Hypothetically, it should be impossible for it to print "Client is disconnected", unless as the result of some race condition. But Naik fixed most of the race conditions in the last release of this branch.

Let me know what happens.

**Comment by forresthopkinsa** [comment]
Also, I should note that you _can_ manually unsubscribe from a topic, if that's what you're going for:

``` java
Subscription sub = mStompClient.topic("/topic/room/" + roomId)
  .subscribeOn(Schedulers.io())
  .observeOn(AndroidSchedulers.mainThread())
  .subscribe(topicMessage -> {
    Log.d(TAG, "Received Room " + topicMessage.getPayload());
    parseMessage(topicMessage.getPayload());
  });

...

sub.unsubscribe();
```

**Comment by creativeprogramming** [comment]
I tried the above code but the `unsubscribe()` method seems to not exist.

How to unsubscribe manually a topic?

**Comment by forresthopkinsa** [comment]
If you look at my code, you can see that `unsubscribe()` is part of the RxJava `Subscription` object.

**Comment by gautamrh** [comment]
Hi Any solution for topic unsubscribing. Nothing seems to be working for me according to above comments

**Comment by forresthopkinsa** [comment]
@gautamrh Why isn't it working? You need to explain what issue you're facing.

**Comment by Chhitij07** [comment]
hey, I'm facing a similar issue. This is what I've done
`Subscription sub;`
`sub= (Subscription) mStompClient.topic("<location>")

                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())

                .subscribe(topicMessage -> {
                    Log.d(TAG, "Received " + topicMessage.getPayload());

                    addItem(mGson.fromJson(topicMessage.getPayload(), EchoModel.class),topicMessage.getPayload());
                });`
The casting of the subscription was forced as I was getting an error without that.
Now when I try to call unsubscribe() on sub, there is no function called unsubscribe that is available for a variable of type Subscription. Everything else is working correctly.

maybe, is it a wrong reference to Subscription?

**Comment by forresthopkinsa** [comment]
You should definitely not be needing that cast. If you're needing to cast something, then you're doing something wrong. Check your imports to make sure you're using the right `Subscription`.

**Here's how you should format your code in Github comments:**

``` java
Subscription sub;
sub = (Subscription) mStompClient.topic("<location>")
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
.subscribe(topicMessage -> {
   Log.d(TAG, "Received " + topicMessage.getPayload());
   addItem(mGson.fromJson(topicMessage.getPayload(), EchoModel.class), topicMessage.getPayload());
});
```

**Comment by NaikSoftware** [comment]
Maybe you are using Subscription from Java 8 JDK? It is must be RxJava2 Subscription..

**Comment by axellageraldinc** [comment]
Same thing happens to me. What I found is `Subscription` from `org.reactivestreams` and when I store the `mStompClient.topic(......)` to `Subscription`, there is an error says **incompatible types**. Required `org.reactivestreams.Subscription` and Found `io.reactivex.disposables.Disposable`. Any thoughts?

**Comment by NaikSoftware** [comment]
@axellageraldinc store to Disposable. Its 'Subscription' in RxJava2.

**Comment by axellageraldinc** [comment]
Okay @NaikSoftware 
My code is like this `Disposable d = mStompClient.topic("/topic/ok")`.
Should I just go with `d.dispose()` to unsubscribe `/topic/ok` topic?

**Comment by NaikSoftware** [comment]
@axellageraldinc yes

**Comment by axellageraldinc** [comment]
Thank you :)
