### ISSUE TITLE
Hi,I want to know "how to unsubscribe stompClient"

### ISSUE THREAD

**Issue by oemers** [NaikSoftware/StompProtocolAndroid#7]
i use like this:
mStompClient.unsubscribePath("/topic/" + lesson_id); but it do not work . can you help me?

**Comment by williamtan89** [comment]
Seems like the author is not active,

Anyway,

Subscription mySubscription = mStompClient.topic("topicPath").subscribe(...);
mySubscription.unsubscribe();//will unsubscribe

**Comment by oemers** [comment]
@williamtan89 Thank you！I had solved it。 like this：

mConnectionProvider.send(new StompMessage(StompCommand.UNSUBSCRIBE,
                        Collections.singletonList(new StompHeader(StompHeader.ID, unsubscribeStr)),null).compile())
                        .subscribe();
