### ISSUE TITLE
hi,please tell me how to with header when mStompClient.send()

### ISSUE THREAD

**Issue by iamsdk** [NaikSoftware/StompProtocolAndroid#75]
sorry ,my english is not good.
i know how to add the head when mStompClient.connect(); 
like this mStompClient.connect(header); 
but how to add the head when send?
erm..can u pull the code on the answer?than u very very much!!!thank you! 
--------a coder from china~

**Comment by iamsdk** [comment]
oh, forget to tell u, i was using the version 1.1.1

**Comment by forresthopkinsa** [comment]
I wrote [an answer](https://github.com/NaikSoftware/StompProtocolAndroid/issues/68#issuecomment-326616784) about headers about a month ago, maybe it can help you. If not, try to be a little more specific with what exactly you're trying to do and why it isn't working.

**Comment by iamsdk** [comment]
i read your sourceCode last night;
this is my understanding;
your StompHeader can  save the targetUrl
like this
new StompHeader(StompHeader.DESTINATION, "/wsd/sendToServer")
and it can save the other header
like 
new StompHeader("otherHead", "otherHead");
`


StompHeader header = new StompHeader("messageType", "receiveOrder");
StompHeader header2 = new StompHeader(StompHeader.DESTINATION, "/wsd/sendToServer");
 List<StompHeader> heads = new ArrayList<>();
 heads.add(header);
heads.add(header2);`
                mStompClient.send(new StompMessage(StompCommand.SEND, heads,"lalala"))`

the "lalala" is message-Body, my code is right?

**Comment by forresthopkinsa** [comment]
Why are you trying to send headers on the `SEND` frame? Normally, headers are sent on the `CONNECT` frame. According to the [STOMP Spec](http://stomp.github.io/stomp-specification-1.2.html#SEND), the only _required_ header on `SEND` frames is the `DESTINATION` header, and [we add that automatically](https://github.com/NaikSoftware/StompProtocolAndroid/blob/b55536b5500e8cdafb61b1040cd46533aa21cf98/lib/src/main/java/ua/naiksoftware/stomp/client/StompClient.java#L124).

So if you're worried about `DESTINATION` headers, that's done automatically when you execute `send("/my/destination", "my data")`.

Now, if you're trying to do something more sophisticated, you can indeed use the [lower-level overload](https://github.com/NaikSoftware/StompProtocolAndroid/blob/b55536b5500e8cdafb61b1040cd46533aa21cf98/lib/src/main/java/ua/naiksoftware/stomp/client/StompClient.java#L131) of that method, like you seem to be trying to do. You would use it like so:

``` java
String json = "{ \"this\": \"is\", \"my\": \"data\" }"

StompHeader dest = new StompHeader(StompHeader.DESTINATION, "/manual/destination");
StompHeader length = new StompHeader("content-length", "64");
StompHeader type = new StompHeader(StompHeader.CONTENT_TYPE, "application/json");

List<StompHeader> headers = new ArrayList<>();
headers.add(dest);
headers.add(length);
headers.add(type);

StompMessage message = new StompMessage(StompCommand.SEND, headers, json);
client.send(message).subscribe(...);
```

Does that answer your question?

**Comment by iamsdk** [comment]
send headers on the SEND frame is the server's require
ok,u solve my question,very very thank u~
have a good day~
