### ISSUE TITLE
StompClient->callSubscribers: works incorrectly

### ISSUE THREAD

**Issue by Aslan125** [NaikSoftware/StompProtocolAndroid#76]
Hi!,
I subscribe on "/topic/entity.*.*.*", but when income message with subscriber "/topic/entity.EntityName.Action.id" subscriber is not called because the callSubscribers method compares:

```java
private void callSubscribers(StompMessage stompMessage) {
        String messageDestination = stompMessage.findHeader(StompHeader.DESTINATION);
        for (String dest : mEmitters.keySet()) {
            if (dest.equals(messageDestination)) {
                for (FlowableEmitter<? super StompMessage> subscriber : mEmitters.get(dest)) {
                    subscriber.onNext(stompMessage);
                }
                return;
            }
        }
    }
```

**Comment by forresthopkinsa** [comment]
Please use [Github-flavored markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) code blocks to format code, like so:

``` java
private void callSubscribers(StompMessage stompMessage) {
  String messageDestination = stompMessage.findHeader(StompHeader.DESTINATION);
  for (String dest: mEmitters.keySet()) {
    if (dest.equals(messageDestination)) {
      for (FlowableEmitter<? super StompMessage> subscriber : mEmitters.get(dest)) {
        subscriber.onNext(stompMessage);
      }
      return;
    }
  }
}
```

And yes, you're right, this library does not support wildcard parsing for topics at the moment. If you need that, you can use the [downstream fork](https://github.com/forresthopkinsa/StompProtocolAndroid), which has support for [RabbitMQ Topic Wildcards](https://www.rabbitmq.com/tutorials/tutorial-five-java.html).

Make sure that you read through the [list of changes](https://github.com/forresthopkinsa/StompProtocolAndroid#changes-in-this-fork), and if you have any problems, I'm always monitoring the issues forum on that project as well.
