### ISSUE TITLE
WebSocket Connection Provider is still connected when disconnect() is called on StompClient

### ISSUE THREAD

**Issue by rs146** [NaikSoftware/StompProtocolAndroid#78]
Hi, I am using the following code to connect to the web socket using STOMP:

`mStompClient = Stomp.over(okhttp3.WebSocket.class, "ws://.../ws");`
`//create headers`
`List<StompHeader> headers = Arrays.asList(stompHeader, stompHeader1, stompHeader2);`
`mStompClient.connect(headers);`

```
mStompClient.topic("/topic/test")
.subscribe(topicMessage -> {
    Log.d("MainActivity", topicMessage.getPayload());
});
```

In the Rx subscription I get the message payload through the debugger. However, when I call `disconnect()` on the `mStompClient` instance, I do not get the message payload in the debugger, but I still get the webs socket messages coming through in the debugger such as:

```
D/WebSocketsConnectionProvider: Emit STOMP message: MESSAGE
 subscription:2178ebf5-2a8b-40b7-aac6-66180bb229ad
 destination:/topic/test
message-id:T_2178ebf5-2a8b-40b7-aac6-66180bb229ad@@sessionjlEB96rYAEQijQb0Hq4GMQ@@3
 redelivered:false
content-length:7
                                                                                                  
testing��
```
This, to me, indicates that it hasn't fully disconnected from the websocket even though it the Rx subscription is no longer being subscribed too as I don't see the message payload anymore in the debugger.

**Comment by rs146** [comment]
We need to add the disconnect code ourselves by adding a `close()` operation to both the OkHttpConnectionProvider and the WebSocketsConnectionProvider (depending on which implementation we're using).

**Comment by forresthopkinsa** [comment]
The intended mechanism for this (in this branch, anyway) is [here](https://github.com/NaikSoftware/StompProtocolAndroid/blob/b55536b5500e8cdafb61b1040cd46533aa21cf98/lib/src/main/java/ua/naiksoftware/stomp/OkHttpConnectionProvider.java#L58) -- basically, when a ConnectionProvider loses all its subscribers (which are added [here](https://github.com/NaikSoftware/StompProtocolAndroid/blob/b55536b5500e8cdafb61b1040cd46533aa21cf98/lib/src/main/java/ua/naiksoftware/stomp/client/StompClient.java#L102) and disposed of [here](https://github.com/NaikSoftware/StompProtocolAndroid/blob/b55536b5500e8cdafb61b1040cd46533aa21cf98/lib/src/main/java/ua/naiksoftware/stomp/client/StompClient.java#L159)), it automatically closes the connection.

At least, that's how it's supposed to work. If you want more fine-grained control, there are downstream branches that function that way.
