### ISSUE TITLE
Draft_17 is deprecated/removed

### ISSUE THREAD

**Issue by marci4** [NaikSoftware/StompProtocolAndroid#79]
Hey,
just so you know, Draft_17 is removed with Java-Websocket 1.3.5.
Please use Draft_6455.

Greetings
marci4

**Comment by forresthopkinsa** [comment]
Thanks for letting us know. 👍

**Comment by forresthopkinsa** [comment]
Fixed in [downstream](https://github.com/forresthopkinsa/StompProtocolAndroid).

**Comment by marci4** [comment]
Thank you!

Closing issue!

Greetings
marci4
