### ISSUE TITLE
New topic subscription after mstompclient.connect

### ISSUE THREAD

**Issue by williamtan89** [NaikSoftware/StompProtocolAndroid#8]
There's a problem with listening to new topic after subscribe..

after mStompClient got connected, I'm trying to call mStompClient.topic(anotherTopic).subscribe(...);

My server can receive a send message but can't receive any response from 'anotherTopic'...

**Comment by NaikSoftware** [comment]
Check server configuration.. Or post client code

**Comment by lmorda** [comment]
I think this is the same as issue #19 which is now resolved

**Comment by NaikSoftware** [comment]
@lmorda yes, its duplicate and resolved
