### ISSUE TITLE
WebLogic server and WebLogicRequestUpgradeStrategy

### ISSUE THREAD

**Issue by michwar** [NaikSoftware/StompProtocolAndroid#86]
Hi,

I have a question about WebLogic and WebLogicRequestUpgradeStrategy.
Every time when I use them I can not connect to the server and I'm getting response code 200 OK instead of 101.
Have you ever tried to connect to the WebLogic?
Do you know any workaround or something that makes it working?
With Tomcat everything works fine.
Is there any way to use different protocol than ws?

**Comment by forresthopkinsa** [comment]
I've never used WebLogic, but a 200 response is typically symptomatic of an endpoint mismatch. Read and understand all the information in #49 and see if it applies to you.
