### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by fmatijevic** [NaikSoftware/StompProtocolAndroid#9]
How do you reconnect with your libary if the connection has failed?
Thanks

**Comment by foomoto** [comment]
Yes. How do you handle Reconnection?

**Comment by NaikSoftware** [comment]
Implemented in https://github.com/NaikSoftware/StompProtocolAndroid/releases/tag/1.1.1

**Comment by AldrichMascarenhas** [comment]
@NaikSoftware There is onError when you attempt to reconnect. Any ideas?

**Comment by forresthopkinsa** [comment]
@AldrichMascarenhas Can you give more details?
