### ISSUE TITLE
Continue to receive messages after calling mStompClient.disconnect()

### ISSUE THREAD

**Issue by nickgibson1** [NaikSoftware/StompProtocolAndroid#99]
I create a connection using the following:

    import okhttp3.WebSocket;
    mStompClient = Stomp.over(WebSocket.class, stompUrl);
    mStompClient.connect(headerList);
    mStompClient.topic(topic).subscribe(...);

And then later I call:
    mStompClient.disconnect();

However, I still continue to see log messages such as:
D/WebSocketsConnectionProvider: Emit STOMP message: MESSAGE ....

It appears that I have not actually disconnected. What can I do to ensure I am actually disconnected?

**Comment by nickgibson1** [comment]
**Solution**
When I submitted this question I was using v1.4.4 of StompProtocolAndroid. Updating to version 1.5.0 fixed it for me.

**Comment by forresthopkinsa** [comment]
Awesome

**Comment by nickgibson1** [comment]
Thanks for a great library by the way.
